function [V,elapse] = ALSH_compress(dataset, model, w)
%   This is a wrapper function of LSH (Locality Sensitive Hashing)  testing.
%
%	Usage:
%	[B,elapse] = LSH_compress(A, model)
%
%	      A: Rows of vectors of data points. Each row is sample point
%     model: The model generated by LSH_learn.
%
%	      B: The binary code of the input data A. Each row is sample point
%    elapse: The coding time (testing time).
%
%
%
%
%   Reference:
%       Anshumali Shrivastava, Ping Li
%	Asymmetric LSH (ALSH) for Sublinear Time Maximum Inner Product Search (MIPS)
%
%
%   version 1.0 --Feb/2018 
%
%   Written by xinyan Dai (xinyanshawn@gmail.com)


tmp_T = tic;

[Nitems, Nfeatures] = size(dataset);
normTerm = zeros(Nitems, model.m);
for k=1:Nitems
   	for i=1:model.m 
		normTerm(k, i) = 0.5 ;
	end
end

normalized_data = [dataset normTerm];



expandedB = repmat(model.B, size(normalized_data, 1), 1);
Ym = (normalized_data * model.A + expandedB) / w ;
V = floor(Ym);

elapse = toc(tmp_T);
end
