function [V,elapse] = LSH_compress(dataset, model, w)
%   This is a wrapper function of LSH (Locality Sensitive Hashing)  testing.
%
%	Usage:
%	[B,elapse] = LSH_compress(A, model)
%
%	      A: Rows of vectors of data points. Each row is sample point
%     model: The model generated by LSH_learn.
%
%	      B: The binary code of the input data A. Each row is sample point
%    elapse: The coding time (testing time).
%
%
%
%
%   Reference:
%
%   Moses S. Charikar: Similarity estimation techniques from rounding
%   algorithms. Proceedings of the thiry-fourth annual ACM symposium on
%   Theory of computing, 2002.  
%
%
%   version 2.0 --Nov/2016 
%   version 1.0 --Jan/2011 
%
%   Written by  Yue Lin (linyue29@gmail.com)
%               Deng Cai (dengcai AT gmail DOT com) 
%   version 3.0 -- Jan/2018
%   Modified by LI Jinfeng (lijinf8@gmail.com)


tmp_T = tic;

expandedB = repmat(model.B, size(dataset, 1), 1);
Ym = (dataset * model.A + expandedB) / w ;
V = floor(Ym);

elapse = toc(tmp_T);
end
